version: '3.8'

networks:
    common:
volumes:
    kafka:
services:
    kafka:
        image: 'bitnami/kafka:latest'
        ports:
            - '9092:9092'
        environment:
            - KAFKA_ENABLE_KRAFT=yes
            - KAFKA_CFG_PROCESS_ROLES=broker,controller
            - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=INTERNAL
            - KAFKA_CFG_LISTENERS=CLIENT://:9092,INTERNAL://:9093
            - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CLIENT:SASL_PLAINTEXT,INTERNAL:SASL_PLAINTEXT
            - KAFKA_CFG_ADVERTISED_LISTENERS=CLIENT://127.0.0.1:9092
            - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=CLIENT
            - KAFKA_BROKER_ID=1
            - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@:9091
            - KAFKA_INTER_BROKER_USER=${CLIENT_USER}
            - KAFKA_INTER_BROKER_PASSWORD=${CLIENT_PASSWORD}
            - KAFKA_CLIENT_USERS=${CLIENT_USER}
            - KAFKA_CLIENT_PASSWORDS=${CLIENT_PASSWORD}
            - KAFKA_CFG_SASL_ENABLED_MECHANISMS=PLAIN
            - KAFKA_CFG_SASL_MECHANISM_CONTROLLER_PROTOCOL=PLAIN
            - KAFKA_CFG_SASL_MECHANISM_INTER_BROKER_PROTOCOL=PLAIN
            # - KAFKA_BROKER_ID=1
            # - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
            # - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://127.0.1:9092
            # - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
            - ALLOW_PLAINTEXT_LISTENER=yes
        volumes:
            - ./kafka:/bitnami/kafka
            # - ~/kafka/data/zookeeper_data:/var/lib/zookeeper/data
            # - ~/kafka/data/zookeeper_log:/var/lib/zookeeper/log
        networks:
            - common